<?php
/**
 * @file
 * A description of what your module does.
 */

/**
 * Implements hook_menu().
 *
 *   Adds a setting page for this module, where admins can choose
 *   a base currency and one or more switchable currencies.
 */
function fixer_io_menu() {

  $items['admin/config/regional/fixer_io'] = array(
    'title' => t('fixer.io Currency Switcher'),
    'description' => t('Choose a base currency.'),
    'weight' => 100,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('fixer_io_settings'),
    'access arguments' => array('administer site configuration'),
    'file' => 'fixer_io.admin.inc'
  );

  return $items;
}

/**
 * Implements hook_cron().
 *
 *   Updates exchange rates on cron run.
 */
function fixer_io_cron() {

  _fixer_io_reload();
}

/**
 * Implements hook_field_formatter_info().
 *
 *   Provides the new field formatter for decimal number fields.
 */
function fixer_io_field_formatter_info() {

  $info = array(
    'fixer_io' => array(
      'label' => t('fixer.io currency switcher'),
      'description' => t('Displays value with currency switcher.'),
      'field types' => array('number_decimal'),
      'settings' => array(
        'currency_symbol' => 'symbol_before',
        'thousand_separator' => '',
        'decimal_separator' => '.',
        'scale' => 2,
      ),
    ),
  );

  return $info;
}

/**
 * Implements hook_field_formatter_settings_form().
 */
function fixer_io_field_formatter_settings_form($field, $instance, $view_mode, $form, &$form_state) {

  $display = $instance['display'][$view_mode];
  $settings = $display['settings'];

  $element = array();
  $element['currency_symbol'] = array(
    '#type' => 'select',
    '#title' => t('Currency symbol position'),
    '#default_value' => $settings['currency_symbol'],
    '#options' => array(
      'none' => t('- None -'),
      'symbol_before' => t('Symbol before number value'),
      'symbol_after' => t('Symbol after number value'),
      'iso_before' => t('ISO code before number value'),
      'iso_after' => t('ISO code after number value'),
    ),
  );

  $element['thousand_separator'] = array(
    '#type' => 'select',
    '#title' => t('Thousand marker'),
    '#default_value' => $settings['thousand_separator'],
    '#options' => array(
      '' => t('<none>'),
      '.' => t('Decimal point'),
      ',' => t('Comma'),
      ' ' => t('Space'),
    ),
  );

  $element['decimal_separator'] = array(
    '#type' => 'select',
    '#title' => t('Decimal marker'),
    '#default_value' => $settings['decimal_separator'],
    '#options' => array(
      '.' => t('Decimal point'),
      ',' => t('Comma')
    ),
  );

  $element['scale'] = array(
    '#type' => 'select',
    '#title' => t('Scale'),
    '#description' => t('The number of digits to the right of the decimal.'),
    '#options' => drupal_map_assoc(range(0, 10)),
    '#default_value' => $settings['scale'],
  );

  return $element;
}

/**
 * Implements hook_field_formatter_settings_summary().
 */
function fixer_io_field_formatter_settings_summary($field, $instance, $view_mode) {

  $display = $instance['display'][$view_mode];
  $settings = $display['settings'];

  $summary = _fixer_io_number_format(1234.1234567890, $settings);

  return $summary;
}

/**
 * Implements hook_field_formatter_view().
 *   Outputs the currency switcher form.
 */
function fixer_io_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {

  $element = array(); // Initialize the var
  $settings = $display['settings']; // get the settings

  switch ($display['type']) {
    case 'fixer_io':

      foreach ($items as $delta => $item) {

        $value = $item['value'];
        $form = drupal_get_form('fixer_io_switcher', $value, $settings);

        $element[$delta] = array(
          '#markup' => render($form),
        );
      }
      break;
  }

  return $element;
}

/**
 * Currency switcher form handler.
 *
 *   Returns the actual switcher form.
 */
function fixer_io_switcher($form, &$form_state, $value, $settings) {

  global $language;

  $fixer_io_default = variable_get('fixer_io_default', 'EUR');
  $default_iso_code = is_array($fixer_io_default) ? $fixer_io_default[$language->language] : $fixer_io_default;
  $base_iso_code = variable_get('fixer_io_base', 'EUR');
  $fixer_io_options = variable_get('fixer_io_options', array(
    'EUR',
    'USD',
    'GBP'
  ));
  $options = array();
  foreach ($fixer_io_options as $key => $iso) {
    if ($iso != '0') {
      $options[$key] = $iso;
    }
  }

  $default_value = $value;
  if ($default_iso_code != $base_iso_code) {
    $default_value = _fixer_io_calculate($default_value, $default_iso_code);
  }
  if (!empty($form_state['values']['fixer_io_switcher'])) {
    $number = _fixer_io_calculate($default_value, $form_state['values']['fixer_io_switcher']);
    if ($form_state['values']['fixer_io_switcher'] == $base_iso_code) {
      $number = $value;
    }
  }
  else {
    $number = $default_value;
  }

  $id = drupal_html_id('fixer-io-container');
  $form['fixer_io_container'] = array(
    '#prefix' => '<div id="' . $id . '">',
    '#type' => 'container',
    '#suffix' => '</div>'
  );

  $form['fixer_io_container']['fixer_io_value'] = array(
    '#prefix' => '<span class="form-item fixer-io value">',
    '#markup' => _fixer_io_number_format($number, $settings),
    '#suffix' => '</span>',
  );

  $form['fixer_io_container']['fixer_io_switcher'] = array(
    '#prefix' => '<div class="form-item fixer-io-inline fixer-io select">',
    '#type' => 'select',
    '#options' => drupal_map_assoc($options),
    '#default_value' => $default_iso_code,
    '#ajax' => array(
      'callback' => 'fixer_io_switcher_ajax_callback',
      'wrapper' => $id,
    ),
    '#suffix' => '</div>',
  );

  return $form;
}

/**
 * Callback for both ajax-enabled buttons.
 *
 *   Returns the whole fixer.io container after the switcher got changed.
 */
function fixer_io_switcher_ajax_callback($form, $form_state) {

  return $form['fixer_io_container'];
}

/**
 * Helper function
 *   which calculates one currency value into another currency.
 *
 * @param $value number
 * @param $iso_code string. Three-letters currency ISO code.
 * @return number
 */
function _fixer_io_calculate($value, $iso_code) {

  $obj = variable_get('fixer_io_rates');

  return $obj->rates->$iso_code * $value;
}

/**
 * Helper function that returns formatted number with prefix/suffix.
 *
 * @param $number number
 * @param $settings array
 * @return string
 */
function _fixer_io_number_format($number, $settings) {

  $fixer_base = variable_get('fixer_io_base', 'EUR');
  $fixer_base_symbol = _fixer_io_symbol($fixer_base);

  $prefix = '';
  $suffix = '';

  switch ($settings['currency_symbol']) {
    case 'symbol_before':
      $prefix = $fixer_base_symbol . ' ';
      break;
    case 'symbol_after':
      $suffix = ' ' . $fixer_base_symbol;
      break;
    case 'iso_before':
      $prefix = $fixer_base . ' ';
      break;
    case 'iso_after':
      $suffix = ' ' . $fixer_base;
      break;
  }

  $formatted_number = number_format($number, $settings['scale'], $settings['decimal_separator'], $settings['thousand_separator']);

  return $prefix . $formatted_number . $suffix;
}

/**
 * Helper function
 *   which pulls current exchange rates from fixer.io and
 *   stores them in the database.
 */
function _fixer_io_reload() {

  // Get current rates from fixer.io
  if ($json = file_get_contents('http://api.fixer.io/latest?base=' . variable_get('fixer_io_base', 'EUR'))) {
    $obj = json_decode($json);
    variable_set('fixer_io_rates', $obj);
  }
}

/**
 * Helper function
 *   which returns currency symbol from given ISO code.
 *   Array taken from @see https://gist.github.com/Gibbs/3920259
 *
 * @param $iso_code string. Three-letters currency ISO code.
 * @return string. HTML code.
 */
function _fixer_io_symbol($iso_code) {

  $currency_symbols = array(
    'AED' => '&#1583;.&#1573;', // ?
    'AFN' => '&#65;&#102;',
    'ALL' => '&#76;&#101;&#107;',
    'AMD' => '',
    'ANG' => '&#402;',
    'AOA' => '&#75;&#122;', // ?
    'ARS' => '&#36;',
    'AUD' => '&#36;',
    'AWG' => '&#402;',
    'AZN' => '&#1084;&#1072;&#1085;',
    'BAM' => '&#75;&#77;',
    'BBD' => '&#36;',
    'BDT' => '&#2547;', // ?
    'BGN' => '&#1083;&#1074;',
    'BHD' => '.&#1583;.&#1576;', // ?
    'BIF' => '&#70;&#66;&#117;', // ?
    'BMD' => '&#36;',
    'BND' => '&#36;',
    'BOB' => '&#36;&#98;',
    'BRL' => '&#82;&#36;',
    'BSD' => '&#36;',
    'BTN' => '&#78;&#117;&#46;', // ?
    'BWP' => '&#80;',
    'BYR' => '&#112;&#46;',
    'BZD' => '&#66;&#90;&#36;',
    'CAD' => '&#36;',
    'CDF' => '&#70;&#67;',
    'CHF' => '&#67;&#72;&#70;',
    'CLF' => '', // ?
    'CLP' => '&#36;',
    'CNY' => '&#165;',
    'COP' => '&#36;',
    'CRC' => '&#8353;',
    'CUP' => '&#8396;',
    'CVE' => '&#36;', // ?
    'CZK' => '&#75;&#269;',
    'DJF' => '&#70;&#100;&#106;', // ?
    'DKK' => '&#107;&#114;',
    'DOP' => '&#82;&#68;&#36;',
    'DZD' => '&#1583;&#1580;', // ?
    'EGP' => '&#163;',
    'ETB' => '&#66;&#114;',
    'EUR' => '&#8364;',
    'FJD' => '&#36;',
    'FKP' => '&#163;',
    'GBP' => '&#163;',
    'GEL' => '&#4314;', // ?
    'GHS' => '&#162;',
    'GIP' => '&#163;',
    'GMD' => '&#68;', // ?
    'GNF' => '&#70;&#71;', // ?
    'GTQ' => '&#81;',
    'GYD' => '&#36;',
    'HKD' => '&#36;',
    'HNL' => '&#76;',
    'HRK' => '&#107;&#110;',
    'HTG' => '&#71;', // ?
    'HUF' => '&#70;&#116;',
    'IDR' => '&#82;&#112;',
    'ILS' => '&#8362;',
    'INR' => '&#8377;',
    'IQD' => '&#1593;.&#1583;', // ?
    'IRR' => '&#65020;',
    'ISK' => '&#107;&#114;',
    'JEP' => '&#163;',
    'JMD' => '&#74;&#36;',
    'JOD' => '&#74;&#68;', // ?
    'JPY' => '&#165;',
    'KES' => '&#75;&#83;&#104;', // ?
    'KGS' => '&#1083;&#1074;',
    'KHR' => '&#6107;',
    'KMF' => '&#67;&#70;', // ?
    'KPW' => '&#8361;',
    'KRW' => '&#8361;',
    'KWD' => '&#1583;.&#1603;', // ?
    'KYD' => '&#36;',
    'KZT' => '&#1083;&#1074;',
    'LAK' => '&#8365;',
    'LBP' => '&#163;',
    'LKR' => '&#8360;',
    'LRD' => '&#36;',
    'LSL' => '&#76;', // ?
    'LTL' => '&#76;&#116;',
    'LVL' => '&#76;&#115;',
    'LYD' => '&#1604;.&#1583;', // ?
    'MAD' => '&#1583;.&#1605;.', //?
    'MDL' => '&#76;',
    'MGA' => '&#65;&#114;', // ?
    'MKD' => '&#1076;&#1077;&#1085;',
    'MMK' => '&#75;',
    'MNT' => '&#8366;',
    'MOP' => '&#77;&#79;&#80;&#36;', // ?
    'MRO' => '&#85;&#77;', // ?
    'MUR' => '&#8360;', // ?
    'MVR' => '.&#1923;', // ?
    'MWK' => '&#77;&#75;',
    'MXN' => '&#36;',
    'MYR' => '&#82;&#77;',
    'MZN' => '&#77;&#84;',
    'NAD' => '&#36;',
    'NGN' => '&#8358;',
    'NIO' => '&#67;&#36;',
    'NOK' => '&#107;&#114;',
    'NPR' => '&#8360;',
    'NZD' => '&#36;',
    'OMR' => '&#65020;',
    'PAB' => '&#66;&#47;&#46;',
    'PEN' => '&#83;&#47;&#46;',
    'PGK' => '&#75;', // ?
    'PHP' => '&#8369;',
    'PKR' => '&#8360;',
    'PLN' => '&#122;&#322;',
    'PYG' => '&#71;&#115;',
    'QAR' => '&#65020;',
    'RON' => '&#108;&#101;&#105;',
    'RSD' => '&#1044;&#1080;&#1085;&#46;',
    'RUB' => '&#1088;&#1091;&#1073;',
    'RWF' => '&#1585;.&#1587;',
    'SAR' => '&#65020;',
    'SBD' => '&#36;',
    'SCR' => '&#8360;',
    'SDG' => '&#163;', // ?
    'SEK' => '&#107;&#114;',
    'SGD' => '&#36;',
    'SHP' => '&#163;',
    'SLL' => '&#76;&#101;', // ?
    'SOS' => '&#83;',
    'SRD' => '&#36;',
    'STD' => '&#68;&#98;', // ?
    'SVC' => '&#36;',
    'SYP' => '&#163;',
    'SZL' => '&#76;', // ?
    'THB' => '&#3647;',
    'TJS' => '&#84;&#74;&#83;', // ? TJS (guess)
    'TMT' => '&#109;',
    'TND' => '&#1583;.&#1578;',
    'TOP' => '&#84;&#36;',
    'TRY' => '&#8356;', // New Turkey Lira (old symbol used)
    'TTD' => '&#36;',
    'TWD' => '&#78;&#84;&#36;',
    'TZS' => '',
    'UAH' => '&#8372;',
    'UGX' => '&#85;&#83;&#104;',
    'USD' => '&#36;',
    'UYU' => '&#36;&#85;',
    'UZS' => '&#1083;&#1074;',
    'VEF' => '&#66;&#115;',
    'VND' => '&#8363;',
    'VUV' => '&#86;&#84;',
    'WST' => '&#87;&#83;&#36;',
    'XAF' => '&#70;&#67;&#70;&#65;',
    'XCD' => '&#36;',
    'XDR' => '',
    'XOF' => '',
    'XPF' => '&#70;',
    'YER' => '&#65020;',
    'ZAR' => '&#82;',
    'ZMK' => '&#90;&#75;', // ?
    'ZWL' => '&#90;&#36;',
  );

  return $currency_symbols[$iso_code];
}
